### ISSUE TITLE
handle the window close event

### ISSUE THREAD

**Issue by DeepakChakravarthy** [DeepakChakravarthy/YoutubeDownloader-FYI#10]
Handle the window close event (user clicking the 'X' button) in a Python Tkinter
      I think we can use **window.destroy()**  to close the Window

@RamkumarMrj  Do you have an Some other effective Idea  to close the Window?

**Comment by RamkumarMrj** [comment]
I do think this is better to close the window.

**Comment by DeepakChakravarthy** [comment]
https://github.com/DeepakChakravarthy/YoutubeDownloader-FYI/commit/4284ef56a43a7dbe548e35239b1e322a7d0325f8

Pull Request Merged
