### ISSUE TITLE
Cursor must be changed when it is near Button

### ISSUE THREAD

**Issue by DeepakChakravarthy** [DeepakChakravarthy/YoutubeDownloader-FYI#2]
![Mouse](https://user-images.githubusercontent.com/42644785/80072201-894cf500-8563-11ea-997b-5c4830d8da12.PNG)

**Change it  to hand cursor**

**Comment by hemakumar0920** [comment]
I commence to solve this issue within a week to enhance the mouse properties when it goes near to any button.
