### ISSUE TITLE
Choosing YouTube's Video Resolution

### ISSUE THREAD

**Issue by RamkumarMrj** [DeepakChakravarthy/YoutubeDownloader-FYI#6]
Choose from **1080p, 720p, 480p, 360p, 240p and 144p** to download the Youtube video

**Comment by divyadharshini03** [comment]
I commence to solve this issue within a  two week to enhance the Youtube video resolution.

**Comment by DeepakChakravarthy** [comment]
@RamkumarMrj  Close this Issue

**Comment by RamkumarMrj** [comment]
@DeepakChakravarthy  ok 👍
